# env: development, staging, canary, production
env: development
server:
  host: 127.0.0.1
  grpc:
    port: 5566
  rest:
    port: 8080
postgres : 
  host: 127.0.0.1
  port: 5432
  dbname: GRPC
  user: postgres
  pass: password
